# This is the header
## This is a subheader
### This is the content of the topic.

* Markdown or .md format is demonstrated

In [27]:
import os
import json
import pandas as pd
from dotenv import load_dotenv

# load .env
load_dotenv()

# load the config
with open("config/config.json", "r") as f:
    config = json.load(f)

print(config["llm"])

{'openai_model': 'gpt-4o-mini', 'gemini_model': 'gemini-1.5-flash', 'temperature': 0.3}

In [9]:
df = pd.read_csv("data/transcripts.csv")

print("Data Loaded")
df.head()

Data Loaded

,call_id,agent_name,transcript,expected_call_type
0,1,Alice,Customer: I was charged twice for my premium t...,billing
1,2,Bob,Customer: My claim has been pending for 2 week...,claims
2,3,Charlie,Customer: This is the third time I'm calling! ...,complaint
3,4,Diana,Customer: Can you explain my coverage details?...,general_query

In [10]:
df.tail(2)

,call_id,agent_name,transcript,expected_call_type
2,3,Charlie,Customer: This is the third time I'm calling! ...,complaint
3,4,Diana,Customer: Can you explain my coverage details?...,general_query

In [28]:
from langchain_openai import ChatOpenAI
from langchain_google_genai import ChatGoogleGenerativeAI

def load_llm(config):
  provider = os.getenv("LLM_PROVIDER")
  if provider == "openai":
    llm = ChatOpenAI(
        model=config["llm"]["openai_model"],
        temperature=config["llm"]["temperature"]
    )
  elif provider == "google":
    llm = ChatGoogleGenerativeAI(
        model=config["llm"]["gemini_model"],
        temperature=config["llm"]["temperature"]
    )
  else:
    raise ValueError("Invalid provider")
  return llm

llm = load_llm(config)
print(f"LLM Loaded for provider: {os.getenv("LLM_PROVIDER")}")

LLM Loaded for provider: openai

In [34]:
response = llm.invoke("Say 'Setup Successful' in one short senence")
print(f"Printing LLM response: {response.content}")

Printing LLM response: Setup successful!